spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  application:
    name: scene-pick-be

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET_NAME}
      stack:
        auto: false

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.project.scenepickbe
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

jwt:
  secret: ${JWT_SECRET}
  access-expiration-minutes: 30
  refresh-expiration-days: 14
  cookie:
    secure: false

tmdb:
  api-token: ${TMDB_API_TOKEN}
  base-url: https://api.themoviedb.org/3
  image-base-url: https://image.tmdb.org/t/p/w500

springdoc:
  swagger-ui:
    withCredentials: true
